### ISSUE TITLE
build warns, errors

### ISSUE THREAD

**Issue by ctzurcanu** [bramp/js-sequence-diagrams#112]
```
...
node_modules/.bin/jison src/grammar.jison -o build/grammar.js.tmp
# After building the grammar, run it through the uglifyjs to fix some non-strict issues.
# Until https://github.com/zaach/jison/issues/285 is fixed, we must do this to create valid non-minified code.
node_modules/.bin/uglifyjs \
		build/grammar.js.tmp -o build/grammar.js \
		--comments all --compress --beautify
WARN: Dropping unreachable code [build/grammar.js.tmp:88,0]
...

jspp src/diagram.js > build/diagram-grammar.js || (rm build/diagram-grammar.js && exit 127)
/bin/sh: jspp: command not found

```
have tried ``` npm install JSPP -g ``` but no fix

solutions?

**Comment by bramp** [comment]
Hey @ctzurcanu you need to `sudo gem install jspp`, instructions available https://github.com/bramp/js-sequence-diagrams#build-requirements

**Comment by ctzurcanu** [comment]
I'm sorry I did not read that with more attention. It built.

**Comment by bramp** [comment]
No problem. I've created #113 to alert you (with instructions on how to fix) if jspp is missing.

**Comment by bramp** [comment]
In fact, I found a way to get rid of jspp, and use a standard npm tools. Meaning Make will just install everything it needs. 73b6dc8e392a9562b88f1f4faea285435e481adb

**Comment by ctzurcanu** [comment]
kudos! I will try to modify your lib to use svg.js instead of raphael. hope to bring you the good news soon.
