### ISSUE TITLE
"note over" can produce a narrowed or absent box if the specified participant order does not match the drawn order.

### ISSUE THREAD

**Issue by workroomprds** [bramp/js-sequence-diagrams#115]
Use the following
Note over A,B:a
Note over B,A:b

In Handdrawn, the note boxes are different sizes – the out-of-order is narrower
In Simple, the box around the note with out-of-order parameters is absent
Pictures attached.
Potential fix identified.

![safari](https://cloud.githubusercontent.com/assets/3080163/8598273/bd2f9f4c-2651-11e5-84a4-e92951b2d7c0.png)
![safari](https://cloud.githubusercontent.com/assets/3080163/8598280/c65a43d8-2651-11e5-9886-a1719bf55267.png)

**Comment by bramp** [comment]
Oh thanks, that's a great bug report.

I guess there are two issues here,
1) The hand/simple box drawing is inconsistent with each other,
2) I most likely assume the note is listed in participant order. A simple
sort should fix that.

Patches and tests welcome, or I will look at this sometime at the weekend.

**Comment by workroomprds** [comment]
I've got a fix on its way...
