### ISSUE TITLE
some chars do not render in handwriting mode in actor even though they are in the font file

### ISSUE THREAD

**Issue by eviltester** [bramp/js-sequence-diagrams#117]
The font file documentation lists the characters supported by the font.

The following characters do not render in hand written mode, but do in simple

~~~~~~~~
Title: Issue: some chars do not render in handwriting mode in actor
ΩμΣΠ⋲Δ∕·ˉŁłŠšŽž−->b:
~~~~~~~~

**Comment by bramp** [comment]
I wrote a simple test, and checked, these are the characters within the hand drawn font:

<img width="1545" alt="screen shot 2015-07-26 at 11 49 21 am" src="https://cloud.githubusercontent.com/assets/160627/8895391/d691e726-338d-11e5-939f-195342daeccc.png">

Additionally, I replaced the ttf fonts with otf versions, that contained slightly more glyphs. Still not all you requested, but they just aren't in the otf files.
