### ISSUE TITLE
char backslash "\" is represented a "/" in hand drawn\n actor name but backslash "\" in simple

### ISSUE THREAD

**Issue by eviltester** [bramp/js-sequence-diagrams#118]
char backslash "\" is represented a "/" in hand drawn\n actor name but backslash "\" in simple

~~~~~~~~
Title: Issue: char backslash "\" is represented a "/" in hand drawn\n actor name but backslash "\" in simple
\->A:
~~~~~~~~

**Comment by bramp** [comment]
Thanks for the issue.

You can see on the font's original site: http://www.dafont.com/daniel.font?text=%5C%2F that the bold font (which I'm using) seems to also have \ wrong :(

I'll see what I can do about fixing that.
