### ISSUE TITLE
Replace Raphael with Snap.svg (http://snapsvg.io).

### ISSUE THREAD

**Issue by bramp** [bramp/js-sequence-diagrams#127]
My plan is to refactor the code so both Raphael and Snap.svg can be used. I will create a Snap only version, and a Snap+Raphael version. This has three benefits:
1) Allowing users to keep updating with Raphael support, until they can move to Snap
2) Allows for easier/better testing between the Raphael and Snap versions, to ensure no regressions creep in.
3) If I can make both work, then I would have hopefully made a clean Theme API, making future changes just as easy.

After a short while I will drop Raphael, and make it clear that new features (such as styling elements) will not be supported.

Raphael supports supports IE6+, Firefox 3.0+, Safari 3.0+, Chrome 5.0+, Opera 9.5+ (using VML as a fallback for SVG).
Snap supports "modern browsers" IE9 and up, Safari, Chrome, Firefox, and Opera.

**Comment by schrepfler** [comment]
The suspension is killing us!
![image](https://cloud.githubusercontent.com/assets/3553/10740565/3348623c-7c23-11e5-9c8b-3913d32b0bd8.png)

**Comment by schrepfler** [comment]
The progress on this seems to have stopped. Any hope of it getting picked up?

**Comment by pfarrell** [comment]
I'm thinking of doing a theme on my fork but if Snap is a reality, I'd rather hold off for it.
Has this enhancement been abandoned?

**Comment by schrepfler** [comment]
I don't think it's abandoned.

**Comment by bramp** [comment]
Sorry, not abandoned, i'm just really really slow at making progress.

**Comment by wdamra** [comment]
Here’s my stab at a Snap SVG version. The demo html file works in Chrome and Edge where I tested, with the js file and font file in the same directory, and access to CDNs for SnapSVG/Underscore/jQuery. 

The js file combines the code from src/diagram.js and src/sequence-diagram.js. I commented out the JISON parsing part while working on this, demo data is loaded inside the html file. 

See readme file for change log. I kept the program structure intact, Raphael-specific calls can be un-commented to create a combined Raphael/Snap SVG version with additional logic if you like. Hope this helps with the progress, nice tool by the way. 


[diagram.zip](https://github.com/bramp/js-sequence-diagrams/files/258263/diagram.zip)
![diagram](https://cloud.githubusercontent.com/assets/19277382/15165293/5769c3ac-16da-11e6-81c9-ba4b3bc73537.png)

**Comment by bramp** [comment]
Very cool. I hope we haven't duplicated much effort, as I had 90% completed
my version of the changes in the svg branch.

Anyway I am travelling right now, but I will take a look ASAP!

**Comment by bramp** [comment]
wdamra@ Just got back from my travels, and realised you didn't send this as a pull request. Would you be able to do so? It'll make it easier to review and accept any changes.

**Comment by schrepfler** [comment]
What happened with this effort, it would still be a great move I think.

**Comment by schrepfler** [comment]
This can be closed now.

**Comment by bramp** [comment]
With v2 we now use Snap.svg or Raphael, with Raphael to be phased out.
