### ISSUE TITLE
why a language required here? why not a json structure?

### ISSUE THREAD

**Issue by GomesNayagam** [bramp/js-sequence-diagrams#135]
This could be a dump question, a simple json structure which could draw the sequence diagram right? should it be language to achieve it? why a compiler. Also a more and more requirement is added the language become complex structure.

coz we use similar and our svg diagram is persist in json in server and render it back to brower. 

should i consider it to be a language rather?

**Comment by bramp** [comment]
JSON is its own language, which was designed for a particular purpose. The sequence diagram language was designed to be easy, simple, and human readable for this purpose alone. 

It has some good properties, for example, even without converting to SVG, it is easy to understand the following diagram:
```
A->B: Send a message
B->A: Responses
```

I don't know what a JSON version would like like, but it wouldn't be as human readable.

**Comment by jessechoward** [comment]
The language/syntax is a perfect match for this as it is both syntactically easy and very human readable. Maybe an export as JSON might be what the OP is looking for but I am not sure of the advantages if any there.

**Comment by GomesNayagam** [comment]
perfect, as the web embrace more and more towards JSON, i personally feel JSON can be a better choice for any DSL as we usually had xml. But yours is super simple for this use case. But if i wanted to persist in a JSON store, this could be a little tricky. BTW Good Work.
