### ISSUE TITLE
Bug in drawing

### ISSUE THREAD

**Issue by janhieber** [bramp/js-sequence-diagrams#138]
![bug](https://cloud.githubusercontent.com/assets/1897479/10726304/294ea724-7bd2-11e5-95e4-f078ac529f65.jpg)

As you can see, it draws "HelperLib" twice. I think this is a bug.

**Comment by janhieber** [comment]
OK, i removed the whitespace in the last line, now it works :P

**Comment by bramp** [comment]
This whitespace issue should no longer be a problem. It was fixed months ago. I'm going to reopen this bug until I double check.

**Comment by bramp** [comment]
Ok this was indeed fixed.
