### ISSUE TITLE
Hand-drawn lines can overlap text, become less readable.

### ISSUE THREAD

**Issue by Billiam** [bramp/js-sequence-diagrams#147]
```
a->b: This is difficult to read
a->b: This line is significantly longer than the one which appears above.
```

![example diagram](https://cloud.githubusercontent.com/assets/242008/13054473/a71f5432-d3cf-11e5-836a-206fae3ca724.png)

As sequence text length increases, the maximum vertical range for the swoop in hand drawn lines also increases.

At the lengths above, that line can run right through the line text. At even longer lengths, the line can appear above it's associated text.

**Comment by mnot** [comment]
In `Raphael.fn.wobble`, try a lower divisor; e.g.,

    var wobble = Math.sqrt( (x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) / 30;

instead of 

    var wobble = Math.sqrt( (x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) / 15;

**Comment by bramp** [comment]
Thanks for the feedback. I've actually reworked the wobble a little, capping how much it can wobble. Going over text should no longer be a problem:
<img width="1072" alt="screen shot 2016-12-27 at 5 15 34 pm" src="https://cloud.githubusercontent.com/assets/160627/21511656/1b8350d6-cc58-11e6-8480-b205a5246025.png">
