### ISSUE TITLE
Add ability to change font-size in basic themes

### ISSUE THREAD

**Issue by Charius** [bramp/js-sequence-diagrams#148]
It would be nice to configure font-size when call drawSVG method

**Comment by bramp** [comment]
This will happen in the 2.0 release. (No ETA on when that will be)

**Comment by bramp** [comment]
Ok this should be possible now that v2 is released.

```javascript
diagram.drawSVG(container, {
  'theme': 'hand', 
  'font-size': 72,
});
```

**Comment by Charius** [comment]
whoa, thanks for your answer! Will check that soon!

**Comment by chetabahana** [comment]
Finally. I set 'font-size': 12, it works as expected. Fit to my web. Thanks @bramp for this great project.
[![diagram](https://user-images.githubusercontent.com/36441664/39671462-fb0e32b4-5142-11e8-99f2-6c14833642f1.png)](https://chetabahana.github.io/#chetabahana-skema)
