### ISSUE TITLE
Any Discourse users here?

### ISSUE THREAD

**Issue by nskerl** [bramp/js-sequence-diagrams#151]
I am trying to create a [Discourse ](http://www.discourse.org/) plugin that uses the js-sequence-diagram library. I am running into a rendering issue where it appears the svg output is at times _squashed_.  I suspect its due to the size of the outer container but I am having some difficulty proving that.  Have you ever encountered such an issue where its sometimes rendered like this?

If anyone here is also a Discourse user you might (eventually) find this useful, and hopefully are able to help me debug it. You can view screenshots of my problem in the link below.

Thanks for the great library!

https://meta.discourse.org/t/help-debugging-sequence-diagram-plugin/40279/9?u=nskerl

**Comment by nskerl** [comment]
I did manage to implement this plugin in Discourse.

You can find it here:  https://github.com/nskerl/discourse-sequence-diagram

I couldn't get "simple" theme to work, so its hard coded to "hand."  If anyone has an ideas as to why simple would render so much differently please let me know.

**Comment by bramp** [comment]
Very cool. Do you have an example of how simple fails?

**Comment by nskerl** [comment]
Yea, check this out. They both work fine in the preview window but when rendered in the main view the simple gets odd dimensions. 

I dont know enough about Discourse's internals to debug this, but I am curious what, if anything, is different between these two themes that might cause this?

![image](https://cloud.githubusercontent.com/assets/782187/14416979/f273adbe-ff64-11e5-8969-17befd8736c2.png)

**Comment by bramp** [comment]
I don't have access to the plugin on discourse, but I can't reproduce this myself. 
![Uploading Screen Shot 2016-12-27 at 5.13.12 pm.png…]()
 I've since released a new version of the library, so if this still occurs after upgrading, then please reopen.
