### ISSUE TITLE
Dead links to Raphaël JS

### ISSUE THREAD

**Issue by mk-pmb** [bramp/js-sequence-diagrams#166]
Neither I nor the Wayback Machine can reach http://raphaeljs.com/ , linked from multiple locations within https://bramp.github.io/js-sequence-diagrams/ .

Nice project anyway, thanks! :+1:

**Comment by bramp** [comment]
Thanks. I've now rolled out support for snap.svg, and deprecated the use of Raphael (in part because they disappeared from the Internet).
