### ISSUE TITLE
Support for single line. 

### ISSUE THREAD

**Issue by Jekkill** [bramp/js-sequence-diagrams#185]
I haven't find any information about this, but is it possible to write HTML something like this: 
`Note over Anna: Hello, how are you? \n Anna -> China: \n Note over China: I'm fine `
And it doesn't show only one note with text 

> Hello, how are you? \n Anna -> China: \n Note over China: I'm fine. 

It will be very usefull, if we dinamycally add information to the page, via javascript, for example.

**Comment by bramp** [comment]
Hopefully you resolved this on your own. If not feel free to reopen.
