### ISSUE TITLE
How to specify which item is on which side

### ISSUE THREAD

**Issue by OwenLearnsToCode** [bramp/js-sequence-diagrams#190]
For example, I would like 'Sender' to be on the left and 'Receiver' to be on the right. However, because my first line is "Receiver->Sender: Sends Public Key", the entire diagram will have Receiver on the left and Sender on the right. How can I resolve this?

**Comment by bramp** [comment]
Use the `participant` keyword to force the order, for example

```
participant Sender
Receiver->Sender: Sends Public Key
```

As Sender is now mentioned first, it is displayed first on the diagram.
