### ISSUE TITLE
Theming Approach

### ISSUE THREAD

**Issue by de-coy** [bramp/js-sequence-diagrams#35]
I've been looking at how to approach themes and wondered if you had any thoughts on it so far.  I can think of a couple of approaches:
1) Extend the existing theme approach but allow more flexibility with line colours, fills etc.
2) Add CSS classes to the individual elements e.g. title, actor, signal, note etc. and use external style sheets to add fill and stroke colours.

My thoughts are that option 1 might become unwieldy as the number of theme options grows larger whereas option 2 keeps a nice separation of concerns. The jQuery initialisation would then look something like this:

``` javascript
$(function() {
    $(".sequence").sequenceDiagram({linestyle: 'hand',themecss:'css/mytheme.css'}); 
});
```

Any thoughts?

**Comment by bramp** [comment]
Ok since v2.0 we use svg.io, which allows styling via CSS! https://github.com/bramp/js-sequence-diagrams#styling

I think this can now be closed.
