### ISSUE TITLE
Printing with PhantomJS 1.9.1

### ISSUE THREAD

**Issue by gitgrimbo** [bramp/js-sequence-diagrams#48]
Hi,

I'm not sure if this is an issue with js-sequence-diagrams, Raphael, PhantomJS or with my diagram, but I'm getting errors when using PhantomJS to print a page with a js-sequence-diagrams generated diagram.

Sample command:

    phantomjs rasterize.js file:///path/to/seq-diag.html test.pdf

I was originally rasterizing/printing a HTML document that used js-sequence-diagrams. That was quite a large document, so I pulled out one of the generated SVG elements and gradually removed sub-elements until I was getting the error with the minimum SVG diagram.

### seq-diag.html

    <!DOCTYPE html>

    <html>

    <body>

    <script src="../src/site/resources/lib/jquery-1.9.1.js"></script>

    <script src="../src/site/resources/lib/raphael-min.js"></script>
    <script src="../src/site/resources/lib/underscore-min.js"></script>
    <script src="../src/site/resources/lib/sequence-diagram-min.beautified.js"></script>

    <pre class="sequence-diagram">
    Andrew->China: Says Hello
    Note right of China: China thinks\nabout it
    China-->Andrew: How are you?
    Andrew->>China: I am good thanks!
    </pre>

    <script>
    (function() {
        console.log("Before render");
        try {
            $(".sequence-diagram").sequenceDiagram({ theme: "simple" });
            console.log("Render success");
        } catch (e) {
            console.log(e);
        }
    }());
    </script>

    </body>

    </html>

### seq-diag.html error

![adobe-reader-drawing-error](https://f.cloud.github.com/assets/1020541/932927/5a5a88a6-004b-11e3-96c8-22fc71f529fa.png)

### simple2.svg

Command:

    phantomjs rasterize.js file:///path/to/simple2.svg test.pdf

SVG:

    
    <svg style="overflow: hidden; position: relative;" height="318" version="1.1" width="475" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <desc style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
        Created with Raphael 2.1.0</desc>
        <defs style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
            <path style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" stroke-linecap="round" d="M5,0 0,2.5 5,5z" id="raphael-marker-block">
            </path>
            <marker style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" id="raphael-marker-endblock55" markerHeight="5" markerWidth="5" orient="auto" refX="2.5" refY="2.5">
                <use style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" xlink:href="#raphael-marker-block" transform="rotate(180 2.5 2.5) scale(1,1)" stroke-width="1.0000" fill="#000" stroke="none">
                </use>
            </marker>
        </defs>
        <path style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" fill="none" stroke="#000000" d="M50,96C50,96,204.95384871959686,96,234.99128912080778,96" stroke-width="2" marker-end="url(#raphael-marker-endblock55)" stroke-dasharray="0">
        </path>
    </svg>

**Comment by bramp** [comment]
Did you ever dig deeper into this problem? or find a solution? If not I'm going to close this bug in a few days.

**Comment by bramp** [comment]
Closing, feel free to reopen if the problem persists.
