### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL 

### ISSUE THREAD

**Issue by josdejong** [bramp/js-sequence-diagrams#49]
When loading the library as available in the [build](https://github.com/bramp/js-sequence-diagrams/blob/master/build/sequence-diagram-min.js) folder, I get an error `Uncaught SyntaxError: Unexpected token ILLEGAL` (running chrome). The version available [on the website](http://bramp.github.io/js-sequence-diagrams/sequence-diagram-min.js) works fine. Both are version 1.0.4...

**Comment by bramp** [comment]
Fixed by https://github.com/cdnjs/cdnjs/commit/e3d38d4b6b9bd74f2897696ad61335e282d0f598
