### ISSUE TITLE
errors on `npm install`

### ISSUE THREAD

**Issue by kermit666** [bramp/js-sequence-diagrams#52]
I can't install the dependencies via `npm install` after downloading the latest version of js-sequence-diagrams. [Error log.](https://gist.github.com/kermit666/7004414)

**Comment by bramp** [comment]
Thanks for reporting the issue. I am unable to reproduce this issue, and I didn't see any red flags in the log file.

I'm going to close, but feel free to reopen if you continue to experience the issue.
