### ISSUE TITLE
Object doesn't support property or method 'getPrototypeOf'

### ISSUE THREAD

**Issue by ghguy** [bramp/js-sequence-diagrams#57]
If you run the tool with IE 8, you will get this error:

SCRIPT438: Object doesn't support property or method 'getPrototypeOf' 
sequence-diagram.js, line 6 character 5248

Seems like js-sequence does not work with IE 8? c.f. http://stackoverflow.com/questions/10919915/ie8-getprototypeof-method

**Comment by bramp** [comment]
getPrototypeOf is coming from jison that generates the grammar. I will file a bug with them, but until then that stackoverflow post lists ways to work around this (with polyfilling)

**Comment by bramp** [comment]
The bug on jison is here: https://github.com/zaach/jison/issues/194

and according to latest browser share data, IE8 makes up ~16% of the population.
