### ISSUE TITLE
Spaces before -> or other arrows

### ISSUE THREAD

**Issue by eightyeight** [bramp/js-sequence-diagrams#58]
Try out these two samples. This generates the desired sequence diagram:

    Jim->  John: Hi
    John-> Jim: Hi

But I like to whitespaceify things so that the code reads more nicely:

    Jim  -> John: Hi
    John -> Jim: Hi

This code creates actors named `Jim__` and `John_` (underscores represent spaces) in addition to the `Jim` and `John` created on the right-hand sides.

In short, it seems like space is stripped from the front of actor names, but not the end. Sorry if this has been raised before - I dug through the closed issues and couldn't see anything that looked similar.

**Comment by bramp** [comment]
Thanks for the report, and thanks for the grammar fix @jonasfj.

This was inadvertently fixed in 16f8ec957e0de19eb1a15432697207a0b87fda3b, and I have added a unit test (8f598c6) to ensure this doesn't happen again.
