### ISSUE TITLE
Comment on 'Rethink the use of Raphael' 

### ISSUE THREAD

**Issue by cschuller** [bramp/js-sequence-diagrams#62]
I read your todo about 'Rethink the use of Raphael' and can fully understand the background behind it. In one of my projects I replaced Raphaël with snapsvg.io, because of its simple and clean approach.

"Snap was written entirely from scratch by the author of Raphaël (Dmitry Baranovskiy), and is designed specifically for modern browsers"
http://snapsvg.io/

**Comment by bramp** [comment]
I would still like this, but it's not high on my TODO list right now, as I've mostly worked around many of the limitations of Raphael.

**Comment by ctzurcanu** [comment]
an even better choice IMO: svg.js

**Comment by bramp** [comment]
Ok, decided we should migrate to snapsvg.io, mainly because StefRave@ submitted a pull request with part of the work done: https://github.com/bramp/js-sequence-diagrams/pull/125

I will close this, and track the migration work in #127
