### ISSUE TITLE
Any desire to make this a service?

### ISSUE THREAD

**Issue by howardroark** [bramp/js-sequence-diagrams#64]
I love this idea, but I especially love the idea of being able to embed these diagrams in markdown during a stream of conscious.  Technical writing is such an important part of the development process and I find markdown to be the most efficient way to get your thoughts out with just enough formatting.  This could compliment that very well.

```
![INITIAL IDEA](http://service/
Alice->Bob: Hello Bob, how are you?\\
Note right of Bob: Bob thinks\\
Bob-->Alice: I am good thanks!)
```

Mainly, I am just wondering if you have had any thoughts around this.  It could be possible with the help of something like PhantomJS.

Great work!

**Comment by bramp** [comment]
Looks like a few people have made solutions to this bug. Closing as no further action is going to be taken by this project.

**Comment by SeanHood** [comment]
@howardroark This get-diagrams implementation sounds exactly what I'm looking for but all of the links are dead. Is the source hosted elsewhere?

**Comment by howardroark** [comment]
Hey @SeanHood ! Yeah I took it down because it was a bit wonky.  Though I was thinking it could be reimplemented with this... https://github.com/kevva/screenshot-stream

Basically just need to make a static page that grabs JSON from a get param and renders the diagram (can be hosted anywhere, like GitHub pages).  Then build a super simple service that passes that URL to `screenshot-stream` and returns the image data as the response.  Since GitHub automatically caches images to a CDN you won't ever really need to store the file.  If you needed to store the file you could add an extra step to upload it to AWS S3 or something.

**Comment by howardroark** [comment]
On second thought... since all this project does it turn a text sequence into svg(xml)... it should be able to run via node and exchange a sequence for svg without the need for an intermediate browser step.  That would be orders of magnitude more efficient.
