### ISSUE TITLE
Issue with frames

### ISSUE THREAD

**Issue by vishalm1** [bramp/js-sequence-diagrams#66]
Hey,

I am trying to draw sequence diagram in a frame. Somehow target was getting modified causing diagram page to open in a new browser window. 

After some troubleshooting I found that variable "name" is not defined in getActor function in diagram.js. After declaring this variable problem was solved. Could you get this change reflected in plugin?

**Comment by bramp** [comment]
Thanks for the report. This was fixed by @magnars in 4c06a396a0077ee2ba58b329fa24b6046254aaee. This should be rolled out in the latest version.
