### ISSUE TITLE
grammar is not defined in the sequence-diagram-min.js:6

### ISSUE THREAD

**Issue by neilhong** [bramp/js-sequence-diagrams#75]
after make the source code, I ran the test/test.html in Chrome(Ubuntu 14.04), and I get the grammar is not defined error in sequence-diagram-min.js:6, so is it my problem ? can you help me

**Comment by davidw** [comment]
I'm seeing this with

    jison 0.4.15
    jshint v2.5.11
    uglify-js 2.4.16

**Comment by jasonarcala-nliven** [comment]
try using jison 0.4.13 and jshint 2.5.10

**Comment by davidw** [comment]
@jasonarcala-nliven thanks, that works!  Not very nice that those guys have broken their API's in point releases.

**Comment by bramp** [comment]
In 15b7916fd8d047e8f31f4ed956ebe01a19c54180 I've forced all build tools (jison/jshint/etc) to the latest versions, and fixed whatever needing fixing. Not only did Jison rename grammar to parser, but it now produces non-strict output, which meant I had to do this hack: 0a3c4e0c05c1150bafaa827b8743c90372b1d34a

So for now this is resolved. Thanks all for debugging.
