### ISSUE TITLE
gh-pages fail because of mixed content errors

### ISSUE THREAD

**Issue by mozfreddyb** [bramp/js-sequence-diagrams#77]
The github pages load through HTTPS but try to fetch resources via HTTP. Modern browsers block this.

This can be fixed through giving explicit https:// URIs for the resources, they should all be available over a secure transport.

You can also write this as `//` and leave out the protocol, to make it protocol-relative.

**Comment by bramp** [comment]
Thanks for the report. This has now been fixed.
