### ISSUE TITLE
Can we get rid of the underscore dependency?

### ISSUE THREAD

**Issue by lipis** [bramp/js-sequence-diagrams#82]

**Comment by bramp** [comment]
We currently use:
```javascript
_.all
 _.isFinite
_.extend
_.each
_.defaults
```
We could write our own alternatives, or refactor the code, however I would like to understand this requirement before I do that. If it matters, we also support lodash, in addition to underscore.

I'm going to close this issue, but feel free to reopen if you are still interested.

**Comment by lipis** [comment]
Yes, maybe it's not worth to remove it.. But the idea is to use as less dependencies as possible, so in order to include this project, we don't need force ourselves to include underscore, lodash, jQuery, etc.. Of course if the project is heavily depending on something like Raphaël, for sure.

The choice is yours :) It's a cool project.. keep it up!

**Comment by bramp** [comment]
Thanks for your feedback. For now I'm going to close this, as I'm not going to fix it.

However, incase this comes up again in the future, perhaps and alternative is I could include both Raphael and Underscore directly into sequence-diagram.js. This would mean the user would no longer need to include them as dependencies, but of course at the cost of increasing the sequence-diagram.js file size.
