### ISSUE TITLE
Path of source map file is wrong

### ISSUE THREAD

**Issue by bennyn** [bramp/js-sequence-diagrams#83]
I am a big fan of **js-sequence-diagrams** but I encountered an error with the reference of the sourcemap file.

You can reproduce this problem when using "js-sequence-diagrams" from a CDN like [CloudFlare](https://www.cloudflare.com/). Just embed the following script: 

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/sequence-diagram-min.js"></script>
```

After doing that, you will see an error in your browser's JavaScript console because it cannot find `http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/build/sequence-diagram-min.js.map`.

The reason for that is pretty easy. The files `sequence-diagram-min.js` and `sequence-diagram-min.js.map` are both stored in the same directory (`build`). So as a developer (or CDN hoster) you will get both files saved in the same place. The problem now is, that the `min.js` file looks for it's source map file in a subdirectory called `build` because of the following declaration: `"file":"build/sequence-diagram-min.js"`.

Let's say you have the minified version stored in a directory called `js/build/`, then it will look for the source map in `js/build/build/`, which is wrong.

When you just copy both files in a directory called `libs`, then the minified version will look for it's source map in `libs/build` which is also wrong. And as a developer you will copy the minified version and the source map in the same directory because that's how the files are distributed (when you resolve them via bower). There are also stored together in this repository here ([build](https://github.com/bramp/js-sequence-diagrams/tree/master/build)).

You can double-check the issue on [CloudFlare](https://www.cloudflare.com/):
- http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/build/sequence-diagram-min.js.map is not available but  [sequence-diagram-min.js](http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/sequence-diagram-min.js) wants to resolve that file
- http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/sequence-diagram-min.js.map is available and [sequence-diagram-min.js](http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/sequence-diagram-min.js) is stored within the same directory

**Comment by abishekrsrikaanth** [comment]
:+1:

**Comment by bramp** [comment]
Thanks for the report. I have taken steps to correct this. Already the map is correctly reported within the minified file. Next I'm ensuring that cdnjs has a copy of the map (which currently they do not). Once cdnjs updates I'll close this bug.

**Comment by bramp** [comment]
Fixed by https://github.com/cdnjs/cdnjs/commit/e3d38d4b6b9bd74f2897696ad61335e282d0f598
