### ISSUE TITLE
Hash tags cannot be drawn

### ISSUE THREAD

**Issue by bennyn** [bramp/js-sequence-diagrams#84]
I wanted to create a diagram which displays the routes of my REST service. But unfortunately "js-sequence-diagrams" cannot render texts which start with a hash (#).

I tried it with this declaration:

```html
<div id="diagram">
  A->B: /rest/#{id}/call
</div>
```

Using the code above, only `A->B: /rest/` will be displayed.

**Comment by bramp** [comment]
# starts a comment, such as
```
A->B: something # TODO fill in more information
```

I'm not sure what a good solution to this would be. We could escape the #, such as \#, or we could say comments must be the first thing on the line. I'm open to other suggestions, but I think limiting comments to being the only thing on the line might be the best solution. Assuming you are ok that actors can't begin with a #?

**Comment by bennyn** [comment]
Hi @bramp, thanks for your reply and Happy New Year!

In my case `A->B: /rest/#{id}/call` the hash sign is not a comment. It's part of the value / text and refers to a markup expression. So it would be nice if the hash tag will be escaped so that it will show up in the rendered diagram.

**Comment by davidw** [comment]
@bramp having either comments on a line to themselves, or being able to quote them would work for me.  Awesome bit of code, by the way - I'm using it to make diagrams of Erlang process interections!
