### ISSUE TITLE
Wishlist: load from file via jquery

### ISSUE THREAD

**Issue by davidw** [bramp/js-sequence-diagrams#90]
It'd be cool to be able to load from an external file using jquery's 'get', so that you'd do something like:

    $(".diagram").sequenceDiagram({theme: 'hand', load: 'sequence.txt'});

Maybe I'll see if I can hack this together.

**Comment by bramp** [comment]
This is a good idea, but I think I would leave this to jQuery to do. Something like this would work:
```javascript
$.get( "sequence.txt", function( data ) {
  $( ".diagram" ).html( data );
  $(".diagram").sequenceDiagram({theme: 'hand'});
});
```

Since I think this is easy enough outside the framework, I'm going to close as won't fix.
