### ISSUE TITLE
duplicate participants

### ISSUE THREAD

**Issue by ktsaou** [bramp/js-sequence-diagrams#91]
Hi,

I am trying to re-arrange the participants, but I only get two of them.

```
title: Sales Flow Diagram

Customer->Seller: What can I buy?
Seller->Provisioner: SEARCH
participant CRM
participant CustomerCare
Provisioner-->Provider: Search Query
Provider-->Provisioner: Search Query Result
Note over Provisioner: Process Results
Provisioner-->NoSQLDB: Store Search Result
Provisioner->Seller: SEARCH RESULTS
Seller->Customer: Here is what I have...
Customer->Seller: I like this one...
Seller->Provisioner: PRICE SELLABLE ITEM
Provisioner-->Provider: Price Query
Provider-->Provisioner: Price Query Result
Note over Provisioner: Process Price Result
Provisioner->NoSQLDB: Store Priced Item
Provisioner->Seller: PRICED ITEM
Seller->Customer: This is all I know about it...
Customer->Seller: OK, I'll buy it...
Seller->CRM: CREATE ORDER
CRM->Seller: NEW ORDER ID
Seller->CRM: ADD PRODUCT (PRICED ITEM) TO ORDER
CRM->Provisioner: BOOK (PRICED ITEM)
Provisioner-->Provider: Book Request
Provider-->Provisioner: Book Reply
Note over Provisioner: Process Booking
Provisioner->NoSQLDB: Store Booking
Provisioner->CRM: BOOK RESULT
CRM->Seller: OK
Seller->Customer: Proceed To Payment...
Customer->CustomerCare: Charge me please...
Note over CustomerCare: Process Payment
CustomerCare->CRM: ORDER PAID
CustomerCare->Customer: Thank you...
```

I also tried adding all participants at the top, but still I get twice all participants.

**Comment by bramp** [comment]
Sorry, I don't quite understand the issue. I see the following image:

![Uploading screenshot-bramp.github.io 2015-01-26 07-28-28.png . . .]()

It has 7 participants, none of which are duplicated.

**Comment by ktsaou** [comment]
But the site shows them twice.
Probably there is an old version at the site?

**Comment by bramp** [comment]
I'm still not understanding. Would you be able to provide a screenshot? I used http://bramp.github.io/js-sequence-diagrams/ to create that diagram.

**Comment by ktsaou** [comment]
of course. Here it is...
![image](https://cloud.githubusercontent.com/assets/2662304/5905587/bfc4b5f0-a599-11e4-9ce7-7c1939905338.png)

**Comment by ktsaou** [comment]
and handwritten:

![image](https://cloud.githubusercontent.com/assets/2662304/5905624/fabd604e-a599-11e4-80de-31e84bb611ab.png)

**Comment by ktsaou** [comment]
As you can see the participants CRM and CustomerCare appear twice.

**Comment by gitgrimbo** [comment]
Hi, for further supporting evidence, I have just pasted the code from [#issue-55494348](#issue-55494348) to http://bramp.github.io/js-sequence-diagrams/ and get the same duplication of participants.  Chrome 35 on Win 7.

**Comment by gitgrimbo** [comment]
Also using the site, the following:

participant A
participant B
participant C
A->C: hello
A->B: hello

renders as:

![image](https://cloud.githubusercontent.com/assets/1020541/5941507/56bc9dea-a709-11e4-82b9-c9f8991dea52.png)

**Comment by bramp** [comment]
Thanks for the additional input. For all the examples I see the correct diagram :/ I tried on a Mac Chrome 40, and Linux Chrome, both were correct. @ktsaou which browser/os are you using? I don't have time write now, I will try and investigate later, and try other browsers.

**Comment by ktsaou** [comment]
I run Chrome `Version 40.0.2214.93 m` on Windows 8.1

I confirm that on Firefox 35.0.1 the issue does not exist.

Thanks

**Comment by gitgrimbo** [comment]
`Diagram.prototype.getActor` - the `for (i in actors)` code gives me the following.  So looks like a rogue CR.

````
> alias
"C"
> actors[i].alias
"C
"
> actors[i].alias.charCodeAt(0)
67
> actors[i].alias.charCodeAt(1)
13
> actors[i].alias.charCodeAt(2)
NaN
> alias.charCodeAt(0)
67
> alias.charCodeAt(1)
NaN
````

**Comment by bramp** [comment]
awesome, so I think a trim() somewhere will help! If I get a chance I will see where, and create a unit test to ensure this doesn't creep in.

**Comment by bramp** [comment]
So I'm pretty sure this is a Windows newline issue. (I'm surprised no one on Windows has noticed this earlier!)

The following test currently fails:
```javascript
	assertSingleActor(Diagram.parse("Participant A\nNote left of A: Hello"), "A");
	assertSingleActor(Diagram.parse("Participant A\r\nNote left of A: Hello"), "A");
```
