### ISSUE TITLE
CDN map URL issue

### ISSUE THREAD

**Issue by krysalead** [bramp/js-sequence-diagrams#96]
Hi,

Great job. 
I am using https://cdnjs.com/ to deliver your library into my application and I have a 404 issue on the map built with the library.
I suppose your script is getting 
http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/build/sequence-diagram-min.js.map
When the CDN host it as
http://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.4/sequence-diagram-min.js.map

For know I doanloaded it.

Thanks & regards

Olivier

**Comment by bramp** [comment]
Thanks, I fixed the tooling in 1a4454f4b078c77, and I will push a new version to cloudflare shortly.

**Comment by bramp** [comment]
Fixed by https://github.com/cdnjs/cdnjs/commit/e3d38d4b6b9bd74f2897696ad61335e282d0f598

**Comment by krysalead** [comment]
Thanks I will update accordingly
